name = "yuki-club-chat"
main = "./worker.js"
compatibility_date = "2026-09-04"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "*"

[durable_objects]
bindings = [
  { name = "CHAT_ROOMS", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]
